# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.152.173:3306/demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shfcpp
  rabbitmq:
    host: 47.108.152.173
    port: 5672
    username: admin
    password: Q1w2e3r4
# mybatis 配置
mybatis:
  # xml文件
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.afei.mybatis.model
  # 驼峰
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: com.afei.mybatis.interception

